Промежуточная сдача. Верстка проекта + propTypes
kurzan/react-burger pull request #1
Opened 2022-11-25 13:24 UTC by kurzan

2022-11-25 14:25 UTC, andryxxa93 requested changes
Вы отлично поработали. Проект соответствует макету, код написан чисто и понятно. Понравилось, что вы правильно типизировали ингредиент.
Есть пару замечаний. Вы можете их исправить сейчас или на финальном этапе сдачи работы.

1. Все компоненты, которые принимают пропсы должны иметь типизацию этих пропсов через propTypes.
2. Есть дублирование типизации, необходимо вынести её в отдельный файл (подробнее см. комментарий к pull-request).
3. Не везде проставлен `isRequired`.
4. Хедер имеет проблему с шириной - 
<img width="1440" alt="Снимок экрана 2022-11-25 в 17 20 45" src="https://user-images.githubusercontent.com/60173362/204004632-06fb8ed8-59e3-4ced-b5a2-ea6e998528b1.png">.

Так же в pull-request вы найдете комментарии как можно улучшить код, их делать не обязательно, но в будущем они помогут вам избежать ошибок и сделать код лучше.

Удачи!

2022-11-25 14:25 UTC, andryxxa93 commented on src/components/app-header/app-header.jsx
> +const NavItem = (props) => {
**Необходимо исправить**
Если у компонента есть пропсы, то необходимо их типизировать через propTypes.

2022-11-25 14:25 UTC, andryxxa93 commented on src/components/app/app.tsx
> +      <section className={styles.main}>
**Можно лучше**
Тут больше подходит тег `main`. Так как он один а `section` может быть много.

2022-11-25 14:25 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +          if(item.type !== 'bun') {
**Можно лучше**
Тут можно вместо тернарного оператора использовать оператор AND `&&`. 
`{ item.type !== 'bun' && <li key={index} ... }`

2022-11-25 14:25 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +  data: PropTypes.arrayOf(PropTypes.shape({
**Необходимо исправить**
Супер, вы правильно типизировали ингредиент, но есть два момента:
1. Нужно вынести типизацию в отдельный файл (`src/utils/types.js`) и оттуда импортировать куда нужно. Иначе у вас получается много дублированного кода, а это противоречит принципу `DRY`.
2. Необходимо так же добавить к полям свойство `isRequired`. Это необходимо чтобы в случае отсутствия какого-то свойства в консоли появилась ошибка.

2022-11-25 18:47 UTC, kurzan commented on src/components/burger-constructor/burger-constructor.jsx
> +          if(item.type !== 'bun') {
Получилось, но для этого пришлось положить все это дело в ReactFragment, так оптимальнее, чем с условием? Просто для реакт фрагмента так же пришлось key добавлять.

2022-11-25 18:47 UTC, kurzan commented on src/components/burger-constructor/burger-constructor.jsx
> +          if(item.type !== 'bun') {
> **Можно лучше** Тут можно вместо тернарного оператора использовать оператор AND `&&`. `{ item.type !== 'bun' && <li key={index} ... }`

Получилось, но для этого пришлось положить все это дело в ReactFragment, так оптимальнее, чем с условием? Просто для реакт фрагмента так же пришлось key добавлять.

2022-11-26 11:14 UTC, andryxxa93 approved these changes
Отличная работа. Всё сделано верно. Можете приступать к финальному этапу сдачи работы! 
Удачи!

2022-11-26 11:14 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    price: PropTypes.number.isRequired
**Можно лучше**
Опять получается, что есть дублирование код. В файле `types` лучше просто протипизировать ингредиент, а вот уже в компонентах конкретно указывать массив это или просто ингредиент.

2022-11-26 11:51 UTC, merged